import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN" className="bg-black text-white antialiased dark">
      <body className="min-h-screen flex flex-col m-0 p-0 bg-black text-white">{children}</body>
    </html>
  );
}
